#!/bin/sh
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ ! "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/init.d/nginx restart
if [ ! "$(/sbin/service nginx status | awk 'NR==1 {print $4}')" == "running..." ]; then
clear
echo "========================================================================="
echo "Nginx can not start! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/tienich/vpssim-restart-service
else
clear
echo "========================================================================="
echo "Nginx restart successful "
/etc/vpssim/menu/tienich/vpssim-restart-service
exit
fi
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/init.d/nginx stop
/etc/init.d/nginx start
if [ ! "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
clear
echo "========================================================================="
echo "Nginx can not start! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/tienich/vpssim-restart-service
else
clear
echo "========================================================================="
echo "Nginx restart successful "
/etc/vpssim/menu/tienich/vpssim-restart-service
exit
fi
fi
fi


if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(/bin/systemctl status  nginx.service| awk 'NR==3 {print $2}')" == "active" ]; then
systemctl start nginx.service
if [ ! "$(/bin/systemctl status  nginx.service| awk 'NR==3 {print $2}')" == "active" ]; then
clear
echo "========================================================================="
echo "Nginx can not start! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/tienich/vpssim-restart-service
else
clear
echo "========================================================================="
echo "Nginx restart successful "
/etc/vpssim/menu/tienich/vpssim-restart-service
exit
fi
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "$(/bin/systemctl status  nginx.service| awk 'NR==3 {print $2}')" == "active" ]; then
systemctl stop nginx.service
systemctl start nginx.service
if [ "$(/bin/systemctl status  nginx.service| awk 'NR==3 {print $2}')" == "active" ]; then
clear
echo "========================================================================="
echo "Nginx restart successful "
/etc/vpssim/menu/tienich/vpssim-restart-service
else
clear
echo "========================================================================="
echo "Nginx can not start! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/tienich/vpssim-restart-service
exit
fi
fi
fi
