#!/bin/bash 
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
clear
echo "========================================================================= "
echo "Memcached is Disable in your VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "$(/bin/systemctl status  memcached.service | awk 'NR==3 {print $2}')" == "inactive" ]; then
clear
echo "========================================================================= "
echo "Memcached is Disable in your VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi

if [ -f /etc/sysconfig/memcached ]; then
clear
printf "=========================================================================\n"
printf "               VPSSIM - Managed VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                          Memcached Manage \n"
printf "=========================================================================\n"
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 

if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
echo "                     Memcached status: Running"
fi

if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
echo "                     Memcached status: Stopped"
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "$(/bin/systemctl status  memcached.service | awk 'NR==3 {print $2}')" == "active" ]; then
echo "         Memcached status: Running - Configed RAM Using: $(/bin/systemctl status  memcached.service | awk 'NR==6 {print $8}') MB"
fi

if [ "$(/bin/systemctl status  memcached.service | awk 'NR==3 {print $2}')" == "inactive" ]; then
echo "                    Memcached status: Stopped"
fi
fi
printf "=========================================================================\n"
echo ""

echo "========================================================================="
echo "RAM for Memcached must be a number within range of (20 - $(calc $( free -m | awk 'NR==2 {print $2}' )/8))."
echo "-------------------------------------------------------------------------"
echo -n "Type in the RAM size you want Memcached use [ENTER]: " 
read memcacheram
if [ "$memcacheram" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, Please fill accurately"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi

if ! [[ $memcacheram -ge 20 && $memcacheram -le $(calc $( free -m | awk 'NR==2 {print $2}' )/8)  ]] ; then  
clear
echo "========================================================================="
echo "$memcacheram is wrong!"
echo "-------------------------------------------------------------------------"
echo "RAM for Memcached must be a number within range of (20 - $(calc $( free -m | awk 'NR==2 {print $2}' )/8))."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi  
        

rm -rf /etc/sysconfig/memcached
cat > "/etc/sysconfig/memcached" <<END
PORT="11211"
USER="memcached"
MAXCONN="10024"
CACHESIZE="$memcacheram"
OPTIONS=""
END
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service memcached restart
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl restart memcached.service
fi
clear
echo "========================================================================="
echo "Config successfully Memcached use $memcacheram MB RAM"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
clear
echo "========================================================================= "
echo "Memcached does not detect on your VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
