#!/bin/sh
. /home/vpssim.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/vpssim/menu/memcache/vpssim-tat-memcache
exit
fi
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
/etc/vpssim/menu/memcache/vpssim-bat-memcache
clear
exit
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "$(/bin/systemctl status  memcached.service | awk 'NR==3 {print $2}')" == "active" ]; then
clear
/etc/vpssim/menu/memcache/vpssim-tat-memcache
exit
fi
if [ "$(/bin/systemctl status  memcached.service | awk 'NR==3 {print $2}')" == "inactive" ]; then
clear
/etc/vpssim/menu/memcache/vpssim-bat-memcache
exit
fi
fi
clear
echo "========================================================================="
echo "Sorry, VPSSIM can not find Memcached in your system !"
vpssim
exit
fi
