#!/bin/bash
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
service memcached restart
clear
echo "========================================================================= "
echo "Restart memcached Successfully"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
else
clear
echo "========================================================================= "
echo "Memcached is Disable in your VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "$(/bin/systemctl status  memcached.service | awk 'NR==3 {print $2}')" == "active" ]; then
systemctl restart memcached.service
clear
echo "========================================================================= "
echo "Restart memcached Successfully"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
else
clear
echo "========================================================================= "
echo "Memcached is Disable in your VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi
