#!/bin/bash 
echo "========================================================================="
echo -n "Type in  the domain [ENTER]: " 
read domain
if [ "$domain" = "" ]; then
clear
echo "========================================================================= "
echo "You typed wrong, please type in accurately"
/etc/vpssim/menu/pagespeed/vpssim-pagespeed-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$domain" =~ $kiemtradomain3 ]]; then
	domain=`echo $domain | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$domain maybe not a domain name!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/pagespeed/vpssim-pagespeed-menu
exit
fi


if [ ! -f /etc/nginx/conf.d/$domain.conf ]; then
if [ ! -f /etc/nginx/conf.d/www.$domain.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $domain "
echo "-------------------------------------------------------------------------"
echo "Please check it again!!"
/etc/vpssim/menu/pagespeed/vpssim-pagespeed-menu
exit
fi
fi


if [ -f /etc/nginx/conf.d/$domain.conf ]; then
if [ "$(grep "include /etc/nginx/ngx_pagespeed.conf;" /etc/nginx/conf.d/$domain.conf)" == "include /etc/nginx/ngx_pagespeed.conf;" ]; then
clear
echo "========================================================================="
echo "$domain is already enable Google Pagespeed !"
/etc/vpssim/menu/pagespeed/vpssim-pagespeed-menu
exit
fi
fi

if [ -f /etc/nginx/conf.d/www.$domain.conf ]; then
if [ "$(grep "include /etc/nginx/ngx_pagespeed.conf;" /etc/nginx/conf.d/www.$domain.conf)" == "include /etc/nginx/ngx_pagespeed.conf;" ]; then
clear
echo "========================================================================="
echo "$domain is already enable Google Pagespeed !"
/etc/vpssim/menu/pagespeed/vpssim-pagespeed-menu
exit
fi
fi


echo "-------------------------------------------------------------------------"
read -r -p "You want to ENABLE Google Pagespeed for $domain ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    cat > "/tmp/pagespeed.sh" <<END
#!/bin/sh
sed -i 's/#include \/etc\/nginx\/ngx_pagespeed.conf;/include \/etc\/nginx\/ngx_pagespeed.conf;/g' /etc/nginx/conf.d/$domain.conf
sed -i 's/#include \/etc\/nginx\/ngx_pagespeed.conf;/include \/etc\/nginx\/ngx_pagespeed.conf;/g' /etc/nginx/conf.d/www.$domain.conf
END
chmod +x /tmp/pagespeed.sh
/tmp/pagespeed.sh
rm -f /tmp/pagespeed.sh
clear
clear
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx restart
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl restart nginx.service
fi
clear
echo "========================================================================= "
echo "Successfully ENABLE Google Pagespeed for $domain"
/etc/vpssim/menu/pagespeed/vpssim-pagespeed-menu
        ;;
    *)
        clear
echo "========================================================================= "
echo "Cancle ENABLE Google Pagespeed for $domain "
/etc/vpssim/menu/pagespeed/vpssim-pagespeed-menu
        ;;
esac
