#!/bin/bash
prompt="Type in your choice (4-Exit):"
options=( "Setup Multisite - Step I" "Setup Multisite - Step II" "Active the sub in VPS" "Exit")
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                      Setup Wordpress Multisite\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in
    
    1) /etc/vpssim/menu/wordpress-multi/vpssim-setup-multisite;;
    2) /etc/vpssim/menu/wordpress-multi/vpssim-setup-multisite-step-2;;
    3) /etc/vpssim/menu/wordpress-multi/vpssim-tao-multisite-wordpress;;
    4) clear && /etc/vpssim/menu/vpssim-tien-ich;;
        *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done



