#!/bin/bash
if [ -f /swapfile ]; then
clear
echo "========================================================================= "
echo "Swap already created! Swap size: $( free -m | awk 'NR==4 {print $2}' ) MB"
echo "-------------------------------------------------------------------------"
echo "You must delete old Swap before create the new one!"
/etc/vpssim/menu/swap/vpssim-them-swap-menu
exit
fi
prompt="Type in your choice:"
options=("Swap 512 MB" "Swap 1 GB" "Swap 2 GB" "Swap 3 GB" "Swap 4 GB" "Swap 6 GB")
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "    Thit function only support VPS KVM & XEN And Swap MAX = 2X RAM\n"
printf "=========================================================================\n"
printf "                            Create Swap\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}" "Exit"; do 

    case "$REPLY" in

    1 ) /etc/vpssim/menu/swap/vpssim-create-swap-512;;
    2 ) /etc/vpssim/menu/swap/vpssim-create-swap-1024;;
    3 ) /etc/vpssim/menu/swap/vpssim-create-swap-2048;;
    4 ) /etc/vpssim/menu/swap/vpssim-create-swap-3072;;
    5 ) /etc/vpssim/menu/swap/vpssim-create-swap-4096;;
    6 ) /etc/vpssim/menu/swap/vpssim-create-swap-6144;;
        
$(( ${#options[@]}+1 )) ) echo "BYE!";  clear && /bin/vpssim;;
     *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done
