#!/bin/sh
. /etc/vpssim/opcache.conf
prompt="Type in your choice:"
options=("Disable Opcache" "Config Zend Opcache" "Clear OPcache")
printf "=========================================================================\n"
printf "                 VPSSIM - Manage VPS/Server by VPSSIM.COM             \n"
printf "=========================================================================\n"
printf "                          Zend OPcache Manage \n"
printf "=========================================================================\n"
printf "       Opcache : Enable - RAM Usage: $opcachesize MB - File cache Max: $opcachephpmax\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}" "Exit"; do 

    case "$REPLY" in
    1 ) /etc/vpssim/menu/opcache/vpssim-tat-opcache;;
    2 ) /etc/vpssim/menu/opcache/vpssim-opcache-change-size;;
    3 ) /etc/vpssim/menu/opcache/vpssim-clear-opcache;;
    
    $(( ${#options[@]}+1 )) ) echo "Bye!";  clear && /bin/vpssim;;
    *) echo "You typed in wrong, Please type in the ordinal number on the list";continue;;

    esac
done
