#!/bin/bash
prompt="Type in your choice(10-Exit):"
options=( "Add Website" "Add website + CODE Blog " "Add website + CODE Forum" "Add website + CODE Gallery" "Add website + CODE Shop" "Add website + Wikicode" "Add Park Domain " "Add Redirect Domain" "List Website Running" "Exit")
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                        Add Website + Code\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


    1) /etc/vpssim/menu/vpssim-them-website;;
    2) clear && /etc/vpssim/menu/addon/website/vpssim-before-them-blog;;
    3) clear && /etc/vpssim/menu/addon/website/vpssim-before-them-forum;;
    4) clear && /etc/vpssim/menu/addon/website/vpssim-before-them-Gallery;;
    5) clear && /etc/vpssim/menu/addon/website/vpssim-before-them-shop;;
    6) clear && /etc/vpssim/menu/addon/website/vpssim-before-them-wikicode;;
    7) /etc/vpssim/menu/vpssim-park-domain;;
    8) /etc/vpssim/menu/vpssim-redirect-domain;; 
    9) /etc/vpssim/menu/vpssim-list-website-tren-vps;; 
    10) clear && vpssim;;
        *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done



