#!/bin/sh
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $3}')" == "stopped" ]; then
clear
echo "========================================================================="
echo "Sorry, PHP-FPM is stopped. Please start it before use this function !"
echo "-------------------------------------------------------------------------"
echo "You can start Php-fpm by Command [ service php-fpm start ]"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')" == "inactive" ]; then
clear
echo "========================================================================="
echo "Sorry, PHP-FPM is stopped."
echo "-------------------------------------------------------------------------"
echo "Please start it before use this function !"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi

if [ "$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')" == "failed" ]; then
clear
echo "========================================================================="
echo "Sorry, PHP-FPM is stopped."
echo "-------------------------------------------------------------------------"
echo "Please start it before use this function !"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
fi


if [ ! "$(grep "display_errors = Off" /etc/php.ini)" == "display_errors = Off" ]; then
if [ ! "$(grep "display_errors = On" /etc/php.ini)" == "display_errors = On" ]; then
clear
echo "========================================================================="
echo "VPSSIM can not check display_errors value "
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
fi

if [ ! -f /etc/php.ini ]; then
clear
echo "========================================================================="
echo "VPSSIM can not find out php.ini in your VPS"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi

if [ "$(grep "display_errors = Off" /etc/php.ini)" == "display_errors = Off" ]; then
/etc/vpssim/menu/tienich/vpssim-dang-tat-display_errors
exit
fi
if [ "$(grep "display_errors = On" /etc/php.ini)" == "display_errors = On" ]; then
/etc/vpssim/menu/tienich/vpssim-dang-bat-display_errors
exit
fi
