#!/bin/sh
. /home/vpssim.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service mysql status | awk 'NR==1 {print $3}')" == "running" ]; then
clear
/etc/vpssim/menu/vpssim-sao-luu-phuc-hoi-database
else
clear
echo "========================================================================="
echo "Sorry, MariaDB dang stopped. Start it before use this function!"
echo "-------------------------------------------------------------------------"
echo "You can start it by command [ service mysql start ]"
vpssim
exit
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl start mariadb.service
if [ "$(/bin/systemctl status  mariadb.service | awk 'NR==3 {print $2}')" == "active" ]; then
clear
/etc/vpssim/menu/vpssim-sao-luu-phuc-hoi-database
else
clear
echo "========================================================================="
echo "Sorry, MariaDB dang stopped. Start it before use this function!"
echo "-------------------------------------------------------------------------"
echo "You can start it by command!"
vpssim
exit
fi
fi