#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo -n "Type in domain you want to download CSR file ( [ENTER]: " 
read domainlaycsr
if [ "$domainlaycsr" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, Please fill accurately"
/etc/vpssim/menu/vpssim-tao-ssl-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$domainlaycsr" =~ $kiemtradomain3 ]]; then
	domainlaycsr=`echo $domainlaycsr | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$domainlaycsr maybe not a domain name!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-tao-ssl-menu
exit
fi 

if [ -f /etc/nginx/ssl/$domainlaycsr/$domainlaycsr.csr ]; then
\cp -uf /etc/nginx/ssl/$domainlaycsr/$domainlaycsr.csr /home/$mainsite/private_html/
clear
echo "========================================================================= "
echo "Link download $domainlaycsr.csr:"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/$domainlaycsr.csr"
echo "========================================================================= "
/etc/vpssim/menu/vpssim-tao-ssl-menu
exit
fi
clear
echo "========================================================================= "
echo "You have not created $domainlaycsr.csr on VPS yet !"
/etc/vpssim/menu/vpssim-tao-ssl-menu
exit
fi
