#!/bin/sh
prompt="Type in your choice(5-Exit):"
options=("On (Off) PhpmyAdmin" "Update Phpmyadmin" "Fix Session error" "Fix can't access to PhpMyadmin" "Exit")
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                            Phpmyadmin Manage \n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/vpssim/menu/vpssim-phpmyadmin;;
    2) /etc/vpssim/menu/vpssim-nang-cap-phpmyadmin;;
    3) /etc/vpssim/menu/vpssim-sua-loi-session;;
    4) /etc/vpssim/menu/vpssim-khong-the-truy-cap-php-myadmin;;
    5) clear && /bin/vpssim;;
    
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done

