#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo -n "Type in website you want find backup link [ENTER]: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, Please fill accurately"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi

if [ ! -f /home/$website/public_html/index.php ]; then
clear
echo "========================================================================="
echo "we can not find out $website in server "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi

if [ -f /home/$mainsite/private_html/backup/$website/*.zip ]; then
find /home/$mainsite/private_html/backup/$website/ -type f -exec basename {} \;  > /etc/vpssim/linkbackup
filename=`cat /etc/vpssim/linkbackup`
echo "Please wait..."
sleep 2
clear
echo "========================================================================="
echo "Discovered $website on server !"
echo "-------------------------------------------------------------------------"
echo "Link download backup: "
echo "-------------------------------------------------------------------------"
echo "http://$mainsite:$priport/backup/$website/$filename"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/backup/$website/$filename"
/etc/vpssim/menu/vpssim-sao-luu
rm -rf /etc/vpssim/linkbackup
else
clear
echo "========================================================================="
echo "You did not create backup for $website yet!"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi
