#!/bin/bash
prompt="Type in your choice (9-Exit):"
options=( "Add Website + PHPBB" "Add Website + XMB" "Add Website + SMF " "Add Website + Punbb " "Add Website + Mybb" "Add Website + MiniBB" "Add Website + FUDforum" "Add Website + Fluxbb" "Exit")
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM  \n"
printf "=========================================================================\n"
printf "                      Add Website + Code Forum \n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


1) rm -r -f website-phpbb && wget -q http://vpssim.com/script/vpssim/addon/website/forum/website-phpbb && chmod +x website-phpbb && clear &&./website-phpbb;;
2) rm -r -f website-XMB && wget -q http://vpssim.com/script/vpssim/addon/website/forum/website-XMB && chmod +x website-XMB && clear &&./website-XMB;;
3) rm -r -f website-smf-forum && wget -q http://vpssim.com/script/vpssim/addon/website/forum/website-smf-forum && chmod +x website-smf-forum && clear &&./website-smf-forum;;
4) rm -r -f website-punbb && wget -q http://vpssim.com/script/vpssim/addon/website/forum/website-punbb && chmod +x website-punbb && clear &&./website-punbb;;
5) rm -r -f website-mybb && wget -q http://vpssim.com/script/vpssim/addon/website/forum/website-mybb && chmod +x website-mybb && clear &&./website-mybb;;
6) rm -r -f website-MiniBB && wget -q http://vpssim.com/script/vpssim/addon/website/forum/website-MiniBB && chmod +x website-MiniBB && clear &&./website-MiniBB;;
7) rm -r -f website-FUDforum && wget -q http://vpssim.com/script/vpssim/addon/website/forum/website-FUDforum && chmod +x website-FUDforum && clear &&./website-FUDforum;;
8) rm -r -f website-Fluxbb && wget -q http://vpssim.com/script/vpssim/addon/website/forum/website-Fluxbb && chmod +x website-Fluxbb && clear &&./website-Fluxbb;;
9) clear && /etc/vpssim/menu/vpssim-them-website-menu;;
        *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done



