#!/bin/bash
prompt="Type in your choice (4-Exit):"
options=( "Add Website + Mediawiki" "Add Website + Dokuwiki" "Add Website + WikkaWiki " "Exit")
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM  \n"
printf "=========================================================================\n"
printf "                     Add Website + Code Wiki \n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


1) rm -r -f website-mediawiki && wget -q http://vpssim.com/script/vpssim/addon/website/wikicode/website-mediawiki && chmod +x website-mediawiki && clear &&./website-mediawiki;;
2) rm -r -f website-dokuwiki && wget -q http://vpssim.com/script/vpssim/addon/website/wikicode/website-dokuwiki && chmod +x website-dokuwiki && clear &&./website-dokuwiki;;
3) rm -r -f website-WikkaWiki && wget -q http://vpssim.com/script/vpssim/addon/website/wikicode/website-WikkaWiki && chmod +x website-WikkaWiki && clear &&./website-WikkaWiki;;
4) clear && /etc/vpssim/menu/vpssim-them-website-menu;;
        *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done



