#!/bin/bash
. /home/vpssim.conf
echo "Please wait...."
sleep 2
rm -r -f /home/$mainsite/private_html/log-secure.log.zip
\cp -uf /var/log/secure /home/$mainsite/private_html/
cd /home/$mainsite/private_html
zip log-secure.log.zip secure
rm -r -f secure
cd
clear
echo "========================================================================= "
echo "Link download Log Secure:"
echo "-------------------------------------------------------------------------"
echo "http://$mainsite:$priport/log-secure.log.zip"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/log-secure.log.zip"

/etc/vpssim/menu/vpssim-eroor-menu

