#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="   
echo -n "Type in the domain : " 
read domainMutilsite
if [ "$domainMutilsite" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, Please fill accurately "
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi


kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$domainMutilsite" =~ $kiemtradomain3 ]]; then
	domainMutilsite=`echo $domainMutilsite | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$domainMutilsite maybe not a domain name !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi

if [ ! -f /etc/nginx/conf.d/$domainMutilsite.conf ]; then
clear
echo "========================================================================="
echo "$domainMutilsite is not exist in the system !"
echo "-------------------------------------------------------------------------"
echo "Please try again"
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi

if [ -f /home/$domainMutilsite/public_html/wp-config-sample.php ]; then
if [ ! -f /home/$domainMutilsite/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$domainMutilsite has wordpress code but not installed!"
echo "-------------------------------------------------------------------------"
echo "Please install wordpress first and try again !"
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi
fi


if [ ! -f /home/$domainMutilsite/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$domainMutilsite is not wordpress blog !"
echo "-------------------------------------------------------------------------"
echo "Please try again."
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi


if [ "$(grep "define('WP_ALLOW_MULTISITE', true);" /home/$domainMutilsite/public_html/wp-config.php)" == "define('WP_ALLOW_MULTISITE', true);" ]; then
if [ "$(grep "define('MULTISITE', true);" /home/$domainMutilsite/public_html/wp-config.php)" == "define('MULTISITE', true);" ]; then
clear
echo "========================================================================="
echo "$domainMutilsite configured for Multisite successfully ."
echo "-------------------------------------------------------------------------"
echo "You can create multisite in wp-admin and enabled the sub by option #3"
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi
fi

if [ "$(grep "define('WP_ALLOW_MULTISITE', true);" /home/$domainMutilsite/public_html/wp-config.php)" == "" ]; then
clear
echo "========================================================================="
echo "You have not done the step I (Option I)"
echo "-------------------------------------------------------------------------"
echo "Take the step I and try again"
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi


if [ "$(grep "define('MULTISITE', true);" /home/$domainMutilsite/public_html/wp-config.php)" == "define('MULTISITE', true);" ]; then
clear
echo "========================================================================="
echo "$domainMutilsite configured for Multisite successfully ."
echo "-------------------------------------------------------------------------"
echo "You can create multisite in wp-admin and enabled the sub by option #3"
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi
echo "Please wait..."
sleep 3

sed -i "/define('WP_ALLOW_MULTISITE', true);/adefine('MULTISITE', true);\ndefine('SUBDOMAIN_INSTALL', true);\ndefine('DOMAIN_CURRENT_SITE', '$domainMutilsite');\ndefine('PATH_CURRENT_SITE', '/');\ndefine('SITE_ID_CURRENT_SITE', 1);\ndefine('BLOG_ID_CURRENT_SITE', 1);" /home/$domainMutilsite/public_html/wp-config.php
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl restart php-fpm.service
fi

clear
echo "========================================================================="
echo "configured Multisite for $domainMutilsite successfully"
echo "-------------------------------------------------------------------------"
echo "Go to $domainMutilsite, login and Add SUB for Multisite"
echo "-------------------------------------------------------------------------"
echo "Then enable the SUB in VPS by option #3."
/etc/vpssim/menu/wordpress-multi/vpssim-wordpress-multisite-menu
exit
fi
