#!/bin/sh
if [ -f /etc/yum.repos.d/epel.repo ]
then
sudo sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
fi
if [ ! -f /bin/calc ]
then
wget -q https://raw.githubusercontent.com/JokerFap/xPanel/Panel/scripts/calc -O /bin/calc && chmod +x /bin/calc
yum -y install psmisc bc gawk gcc sendmail
yum -y -q install virt-what unzip sudo net-tools iproute iproute2
fi
if [ $(id -u) != "0" ]; then
    printf "Error: You have to login by user root!\n"
    exit
fi

if [ -f /var/cpanel/cpanel.config ]; then
echo "Your Server installed WHM/Cpanel, if you want to use  xPanel"
echo "Lets rebuild VPS, you should use centos 6 or 7 - 64 bit"
echo "Bye !"
exit
fi

if [ -f /etc/psa/.psa.shadow ]; then
echo "Server installed Plesk, if you want to use xPanel"
echo "Lets rebuild VPS, you should use centos 6 or 7 - 64 bit"
echo "Bye !"
exit
fi

if [ -f /etc/init.d/directadmin ]; then
echo "Your Server installed DirectAdmin, if you want to use xPanel"
echo "Lets rebuild VPS, you should use centos 6 or 7 - 64 bit"
echo "Bye !"
exit
fi

if [ -f /etc/init.d/webmin ]; then
echo "Your Server installed webmin, if you want to use xPanel"
echo "Lets rebuild VPS, you should use centos 6 or 7 - 64 bit"
echo "Bye !"
exit
fi

if [ -f /etc/xpanel/xpanel.conf ]; then
clear
echo "========================================================================="
echo "========================================================================="
echo "Your Server is installed xPanel"
echo "Use command xpanel to access xPanel menu"
echo "Bye !"
echo "========================================================================="
echo "========================================================================="
rm -r -f install
exit
fi
clear
prompt="Type in your choice:"
options=( "PHP 5.6" "PHP 5.5" "PHP 5.4" "Exit" )
echo "========================================================================="
echo "                \e[32mxPanel\e[0m - Manage VPS/Server by JokerFap               "
echo "========================================================================="
echo "                          xPanel Setup Menu                                 "
echo "========================================================================="
echo "                      Please choose PHP version           "
echo "========================================================================="

PS3="$prompt"
select opt in "${options[@]}" ; do 
    case "$REPLY" in
    1) clear && rm -r -f xpanel56 && wget -q https://raw.githubusercontent.com/JokerFap/xPanel/Panel/scripts/centos$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))/xpanel56 && chmod +x xpanel56 && clear && ./xpanel56;;
    2) clear && rm -r -f xpanel55 && wget -q https://raw.githubusercontent.com/JokerFap/xPanel/Panel/scripts/centos$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))/xpanel55 && chmod +x xpanel55 && clear &&  ./xpanel55;;
    3) clear && rm -r -f xpanel54 && wget -q https://raw.githubusercontent.com/JokerFap/xPanel/Panel/scripts/centos$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))/xpanel54 && chmod +x xpanel54 && clear && ./vxpanel54;;
    4) clear && echo "You cancle setup xPanel on this server!" && rm -r -f install && killall -g install;;    
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac
done
