#!/bin/sh
. /home/vpssim.conf
if [ $(id -u) != "0" ]; then
    printf "Error ! VPSSIM run only with root user !\n"
    exit
fi
prompt="Type in your choice:"
options=("Add Website & Code" "Remove website" "Backup code & Config" "Check & Block IP DOS" "Database Manage" "PhpMyadmin Manage" "Zend OPcache Manage" "Google pagespeed Manage" "Memcached Manage" "Swap Manage" "Cronjob Manage" "CSF Firewall Manage" "IPtables Firewall Manage" "Setup SSL (https)" "Download Log file" "Tools - Addons" "Upgrade / Downgrade PHP" "Server Status" "Update VPSSIM" "Exit")
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM                \n"
printf "=========================================================================\n"
printf "                             VPSSIM Menu                                \n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) clear && /etc/vpssim/menu/vpssim-befor-them-website-menu;;
    2) /etc/vpssim/menu/vpssim-befor-xoa-website;;
    3) clear && /etc/vpssim/menu/vpssim-sao-luu;;
    4) clear && /etc/vpssim/menu/vpssim-kiem-tra-ddos;;
    5) clear && /etc/vpssim/menu/vpssim-befor-them-xoa-database;;
    6) clear && /etc/vpssim/menu/vpssim-phpmyadmin-menu;;
    7) clear && /etc/vpssim/menu/opcache/vpssim-before-opcache;;
    8) clear && /etc/vpssim/menu/pagespeed/vpssim-pagespeed-menu;;
    9) clear && /etc/vpssim/menu/memcache/vpssim-before-memcache-menu;;
    10) clear && /etc/vpssim/menu/swap/vpssim-them-swap-menu;;
    11) clear && /etc/vpssim/menu/crontab/vpssim-cronjob-menu;;
    12) /etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-before-menu;;
    13) clear && /etc/vpssim/menu/vpssim-iptables-firewall-manager-menu;;
    14) clear && /etc/vpssim/menu/vpssim-tao-ssl-menu;;
    15) clear && /etc/vpssim/menu/vpssim-eroor-menu;;
    16) clear && /etc/vpssim/menu/vpssim-tien-ich;;
    17) clear && /etc/vpssim/menu/nangcap-php/vpssim-updown-php;;
    18) clear && /etc/vpssim/menu/vpssim-vps-info;;
    19) /etc/vpssim/menu/vpssim-nang-cap-scripts;;
    20) clear && echo "Thank you for Using VPSSIM. Bye !" && killall -g vpssim && clear;;  
    *) echo "You typed wrong, please type in the ordinal number on the list";continue;;

    esac
done
 
