#!/bin/sh
. /etc/xpanel/xpanel.conf
if [ $(id -u) != "0" ]; then
    printf "Error ! xPanel run only with root user !\n"
    exit
fi
prompt="Type in your choice:"
options=("Add Website" "Remove website" "Backup code & Config" "Check & Block IP DOS" "Database Manage" "PhpMyadmin Manage" "Zend OPcache Manage" "Google pagespeed Manage" "Memcached Manage" "Swap Manage" "Cronjob Manage" "CSF Firewall Manage" "IPtables Firewall Manage" "Setup SSL (https)" "Download Log file" "Tools - Addons" "Upgrade / Downgrade PHP" "Server Status" "Update xPanel" "Exit")
printf "=========================================================================\n"
printf "               xPanel - Manage VPS/Server by JokerFap                \n"
printf "=========================================================================\n"
printf "                             xPanel Menu                                \n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) clear && /etc/xpanel/menu/website/add-website;;
    2) /etc/xpanel/menu/befor-remove-website;;
    3) clear && /etc/xpanel/menu/backup;;
    4) clear && /etc/xpanel/menu/check-ddos;;
    5) clear && /etc/xpanel/menu/vpssim-befor-them-xoa-database;;
    6) clear && /etc/xpanel/menu/phpmyadmin-menu;;
    7) clear && /etc/xpanel/menu/opcache/vpssim-before-opcache;;
    8) clear && /etc/xpanel/menu/pagespeed/pagespeed-menu;;
    9) clear && /etc/xpanel/menu/memcache/vpssim-before-memcache-menu;;
    10) clear && /etc/xpanel/menu/swap/vpssim-them-swap-menu;;
    11) clear && /etc/xpanel/menu/crontab/vpssim-cronjob-menu;;
    12) /etc/xpanel/menu/CSF-Fiwall/vpssim-csf-firewall-before-menu;;
    13) clear && /etc/xpanel/menu/vpssim-iptables-firewall-manager-menu;;
    14) clear && /etc/xpanel/menu/vpssim-tao-ssl-menu;;
    15) clear && /etc/xpanel/menu/vpssim-eroor-menu;;
    16) clear && /etc/xpanel/menu/vpssim-tien-ich;;
    17) clear && /etc/xpanel/menu/upgrade-php/vpssim-updown-php;;
    18) clear && /etc/xpanel/menu/vps-info;;
    19) /etc/xpanel/menu/vpssim-nang-cap-scripts;;
    20) clear && echo "Thank you for Using xPanel. Bye !" && killall -g vpssim && clear;;  
    *) echo "You typed wrong, please type in the ordinal number on the list";continue;;

    esac
done
 
