#!/bin/bash
prompt="Type in your choice(5-Exit):"
options=( "Add Website" "List Website Running" "Exit")
printf "=========================================================================\n"
printf "               \e[32mxPanel\e[0m - Manage VPS/Server by JokerFap \n"
printf "=========================================================================\n"
printf "                        Add Website\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in
    1) /etc/xpanel/menu/website/add-website;;
    2) /etc/xpanel/menu/website/list-website;; 
    3) clear && xpanel;;
        *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac
done
