#!/bin/sh
. /home/vpssim.conf
echo "========================================================================="
echo "With less RAM VPS, sometime free RAM is too low, MySQL Databbase is stop"
echo "-------------------------------------------------------------------------"
echo "This function will re-start it after 5 mins if MariaDB service die"
echo "-------------------------------------------------------------------------"
echo "If MariaDB service have never randomly Stop, do not use this function!"
echo "-------------------------------------------------------------------------"
read -r -p "You want to enable [Auto re-start MySQL Server] function ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
(crontab -u root -l ; echo "*/5 * * * * auto-start-mysql") | crontab -u root -
echo "Please wait..."
sleep 2
    clear
    echo "========================================================================="
echo "Enable [Auto re-start MySQL Server] function successfully !"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
    *)
       clear
    echo "========================================================================="
   echo "You cancel Turn ON  [Auto re-start MySQL Server] function !"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
esac
exit
fi
