#!/bin/sh
printf "Ban hay lua chon phien ban PHP muon su dung:\n"
prompt="Nhap vao lua chon cua ban [1-3]: "
options=("GMT" "GMT+" "GMT+" "GMT+" "GMT+" "GMT+" "GMT+" "GMT+" "GMT+" "GMT+" "GMT+" "GMT+" "GMT+" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "GMT-" "PHP 5.4")
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) muigio="GMT"; break;;
    2) muigio="GMT+1"; break;;
    3) muigio="GMT+2"; break;;
    4) muigio="GMT+3"; break;;
    5) muigio="GMT+4"; break;;
    6) muigio="GMT+5"; break;;
    7) muigio="GMT+6"; break;;
    8) muigio="GMT+7"; break;;
    9) muigio="GMT+8"; break;;
    10) muigio="GMT+9"; break;;
    11) muigio="GMT+10"; break;;
    12) muigio="GMT+11"; break;;
    13) muigio="GMT+12"; break;;
    14) muigio="GMT+13"; break;;
    15) muigio="GMT+14"; break;;
    16) muigio="GMT-1"; break;;
    17) muigio="GMT-2"; break;;
    18) muigio="GMT-3"; break;;
    19) muigio="GMT-4"; break;;
    20) muigio="GMT-5"; break;;
    21) muigio="GMT-6"; break;;
    22) muigio="GMT-7"; break;;
    23) muigio="GMT-8"; break;;
    24) muigio="GMT-9"; break;;
    25) muigio="GMT-10"; break;;
    26) muigio="GMT-11"; break;;
    27) muigio="GMT-12"; break;;
  
    
    3) muigio="GMT+"; break;;
    $(( ${#options[@]}+1 )) ) printf "\nChao tam biet....!\n"; break;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren danh sach";continue;;
    esac
    
done






if [ "$muigio" = "5.6" ]; then
	yum -y --enablerepo=remi,remi-php56 install nginx php-fpm php-common php-gd php-mysql php-pdo php-xml php-mbstring php-mcrypt php-curl unzip nano
elif [ "$muigio" = "5.5" ]; then
	yum -y --enablerepo=remi,remi-php55 install nginx php-fpm php-common php-gd php-mysql php-pdo php-xml php-mbstring php-mcrypt php-curl unzip nano
else
	yum -y --enablerepo=remi install nginx php-fpm php-common php-gd php-mysql php-pdo php-xml php-mbstring php-mcrypt php-curl unzip nano
fi










#!/bin/sh
yes | cp /usr/share/zoneinfo/Etc/GMT+9 /etc/localtime
clear
echo "========================================================================="
echo "The VPS Time is:"
echo "-------------------------------------------------------------------------"
date
/etc/vpssim/menu/vpssim-tien-ich
