#!/bin/sh
. /home/vpssim.conf
if [ ! -d "/home/$mainsite/private_html/vpsinfo" ]; then
mkdir -p /home/$mainsite/private_html/vpsinfo
fi
echo "========================================================================= "
echo -n "Type in any 5 characters (letters and numbers) [ENTER]: " 
read abcd
if [ "$abcd" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, Please fill accurately"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi

if [[ ! ${#abcd} -ge 5 ]]; then
clear
echo "========================================================================="
echo "The security code make your list files more security."
echo "-------------------------------------------------------------------------"
echo "It must be at least 5 characters long. Please try again !"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi 
echo "Please wait...."
sleep 2
curl ipinfo.io > /etc/vpssim/ipvpsinfo.txt
echo "CHECK SERVER INFOMATION BY VPSSIM" > /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=========================================================================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "IP INFOMATION" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=========================================================================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "IP VPS: $serverip" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "Host name: $(cat /etc/vpssim/ipvpsinfo.txt | awk 'NR==3 {print $2,$3,$4,$5,$6}')" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "City: $(cat /etc/vpssim/ipvpsinfo.txt | awk 'NR==4 {print $2,$3,$4,$5,$6}')" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "Region: $(cat /etc/vpssim/ipvpsinfo.txt | awk 'NR==5 {print $2,$3,$4,$5,$6}')" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "Country: $(cat /etc/vpssim/ipvpsinfo.txt | awk 'NR==6 {print $2,$3,$4,$5,$6}')" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "Latitude/Longitude: $(cat /etc/vpssim/ipvpsinfo.txt | awk 'NR==7 {print $2,$3,$4,$5,$6}')" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "Network: $(cat /etc/vpssim/ipvpsinfo.txt | awk 'NR==8 {print $2,$3,$4,$5,$6}')" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=========================================================================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "DISC INFOMATION" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=========================================================================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
df -h >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=========================================================================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "BASIC INFOMATION" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=========================================================================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
tencpu=$(cat /proc/cpuinfo|grep name|head -1|awk '{ $1=$2=$3=""; print }')
soloi=$(cat /proc/cpuinfo|grep MHz|wc -l)
tocdo=$(cat /proc/cpuinfo|grep MHz|head -1|awk '{ print $4 }')
ramsize=$(free -m | awk 'NR==2'|awk '{ print $2 }')
swapserver=$(free -m | awk 'NR==4'| awk '{ print $2 }')
tocdohdd=$( (dd if=/dev/zero of=test_$$ bs=64k count=16k conv=fdatasync &&rm -f test_$$) 2>&1 | tail -1| awk '{ print $(NF-1) $NF }')
echo "VPS Type : $(virt-what)" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "CPU type : $tencpu"  >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "Number of cores : $soloi"  >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "CPU frequency : $tocdo MHz"  >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "RAM : $ramsize MB"  >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "Swap : $swapserver MB"  >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "I/O speed : $tocdohdd"  >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=========================================================================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "CPU DETAIL INFOMATION" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=========================================================================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
cat /proc/cpuinfo >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
echo "=================================== The End =============================================" >> /home/$mainsite/private_html/vpsinfo/vpssim-$abcd.txt
rm -r -f /etc/vpssim/ipvpsinfo.txt
clear
clear
echo "========================================================================= "
echo "Link to view server info:"
echo "-------------------------------------------------------------------------"
echo "http://$mainsite:$priport/vpsinfo/vpssim-$abcd.txt"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/vpsinfo/vpssim-$abcd.txt"
/etc/vpssim/menu/vpssim-tien-ich
