#!/bin/sh
. /home/vpssim.conf


if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 

if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $3}')" == "stopped" ]; then
clear
echo "========================================================================="
echo "PHP-FPM Stopped !"
echo "-------------------------------------------------------------------------"
echo "You can not install or remove Ioncube Loader"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
fi


if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 

if [ "$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')" == "inactive" ]; then
clear
echo "========================================================================="
echo "PHP-FPM Stopped !"
echo "-------------------------------------------------------------------------"
echo "You can not install or remove Ioncube Loader"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
if [ "$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')" == "failed" ]; then
clear
echo "========================================================================="
echo "PHP-FPM Stopped !"
echo "-------------------------------------------------------------------------"
echo "You can not install or remove Ioncube Loader"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
fi
/etc/vpssim/menu/tienich/vpssim-ioncube-cai-dat-remove
exit
fi
