#!/bin/bash
. /home/vpssim.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $3}')" == "stopped" ]; then
clear
echo "========================================================================="
echo "PHP-FPM  Stopped!"
echo "You can not install or re-install IMAGICK"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
fi


if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')" == "inactive" ]; then
clear
echo "========================================================================="
echo "PHP-FPM  Stopped!"
echo "You can not install or re-install IMAGICK"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
if [ "$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')" == "failed" ]; then
clear
echo "========================================================================="
echo "PHP-FPM  Stopped!"
echo "You can not install or re-install IMAGICK"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
fi
echo "========================================================================="
read -r -p "You want to install / re-install imagick ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
echo "Ok ! please wait ...."
sleep 2
clear
rm -r -f /etc/php.d/imagick.ini 
pecl uninstall imagick
clear
echo "========================================================================="
echo "Next, do not type anything and press [Enter] when see sections below"
echo "-------------------------------------------------------------------------"
echo "Please provide the prefix of Imagemagick installation [autodetect] :"
echo "========================================================================="
sleep 8
pecl install imagick
echo "extension=imagick.so" > /etc/php.d/imagick.ini
clear
clear
echo "========================================================================="
echo "You have finished install or re-install IMAGICK"
/etc/vpssim/menu/vpssim-tien-ich
 ;;
    *)
    clear
    echo "========================================================================="
   echo "You cancel install / re-install Imagick"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
esac
clear
    echo "========================================================================="
    echo "You cancel install / re-install Imagick"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
