#!/bin/sh
. /home/vpssim.conf
 
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
/etc/init.d/php-fpm start
test_php=$(/sbin/service php-fpm status | awk 'NR==1 {print $3}')
if [ "$test_php" == "stopped" ]; then
clear
echo "========================================================================="
echo "PHP-FPM can not start! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/tienich/vpssim-restart-service
exit
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl stop php-fpm.service
systemctl start php-fpm.service
test_php=$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')
if [ "$test_php" == "inacctive" ]; then
clear
echo "========================================================================="
echo "PHP-FPM can not start! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/tienich/vpssim-restart-service
exit
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl stop php-fpm.service
systemctl start php-fpm.service
test_php=$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')
if [ "$test_php" == "failed" ]; then
clear
echo "========================================================================="
echo "PHP-FPM can not start! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/tienich/vpssim-restart-service
exit
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
/etc/init.d/php-fpm restart
else
systemctl restart php-fpm.service
fi
clear
echo "========================================================================="
echo "PHP-FPM restart successful "
/etc/vpssim/menu/tienich/vpssim-restart-service
exit
fi



