#!/bin/sh
prompt="Type in your choice:"
options=("Enable (disable) Opcache" "Config Zend Opcache" "Clear OPcache")
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM             \n"
printf "=========================================================================\n"
printf "                         Zend OPcache Manage \n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" "Exit"; do 

    case "$REPLY" in
    1 ) /etc/vpssim/menu/vpssim-before-opcache;;
    2 ) /etc/vpssim/menu/vpssim-opcache-change-size;;
    3 ) /etc/vpssim/menu/vpssim-clear-opcache;;
    
    $(( ${#options[@]}+1 )) ) echo "Bye!";  clear && /bin/vpssim;;
    *) echo "You typed in wrong, Please type in the ordinal number on the list";continue;;

    esac
done
