#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
read -r -p "Do you want to enable Zend Opcache ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
	mv /etc/php.d/opcache.bak /etc/php.d/opcache.ini
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
else
systemctl restart php-fpm.service
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
test_php=$(/sbin/service php-fpm status | awk 'NR==1 {print $3}')
if [ "$test_php" == "stopped" ]; then
clear
echo "========================================================================="
echo "PHP-FPM can not restart! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi
fi


if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
test_php=$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')
if [ "$test_php" == "inactive" ]; then
clear
echo "========================================================================="
echo "PHP-FPM can not restart! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi
fi


if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
test_php=$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')
if [ "$test_php" == "failed" ]; then
clear
echo "========================================================================="
echo "PHP-FPM can not restart! "
echo "-------------------------------------------------------------------------"
echo "Maybe you did a wrong config  !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
else
systemctl restart php-fpm.service
fi
clear
echo "========================================================================="
	echo "Enable Zend OPcache successfully  !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
        ;;
    *)
        clear
echo "========================================================================="
echo "You typed wrong, Please fill accurately"
/etc/vpssim/menu/opcache/vpssim-before-opcache
        ;;
esac
